name = "npflared"
main = "src/index.ts"
compatibility_date = "2024-11-24"

compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

# Custom domain setup - configure in Cloudflare dashboard
# [[routes]]
# pattern = "npm.coalesce-labs.ai"
# custom_domain = true

[vars]
FALLBACK_REGISTRY_ENDPOINT = "https://registry.npmjs.org"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "coalesce-labs-npm-repository"

[[d1_databases]]
binding = "DB"
database_name = "npflared-db"
database_id = "cc8e2c56-e6a1-431b-9d5d-de0bcd99eb69"
